model_params:
  learning_rate: 0.001
  batch_size: -1
  d_feat: 82 # input feature size
  hidden_size: 64
  dropout: 0.2
  num_factor: 16
  num_layers: 2
  max_epochs: 50
  save_path: "results/"
  early_stopping: 5
  seed: 42
  l1_reg: 0.01

data_params:
  train_length: 1260 # 5 year
  valid_length: 252 # 2 year
  test_length: 252 # 1 year
  data_path: "data/Data_With_Residual_New.csv"
  target: "1d_return"
  seq_len: 20
  shuffle: False
  refit: 252 # every year refit model
  using_buffer: True